remote_theme: pages-themes/dinky@v0.2.0
title: [Augmented Software Visualization]
description: [<a href="https://shonan.nii.ac.jp/seminars/192/">Shonan Meeting N°192</a>]
github:
  is_project_page: false
